version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    container_name: auth-id-app
    env_file: .env
    ports:
      - "9090:9090"
    depends_on:
      - postgres-master

   # volumes:
    #  - ./:./go/auth-id
    networks:
      - services
  postgres-master:
    image: postgres:15
    container_name: auth-id-postgres
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ../auth-id-postgres-data:/var/lib/postgresql/data
      - ./migration:/opt/migration
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - services
networks:
  services:
    driver: bridge